// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240613161624_Description")]
    partial class Description
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.TodoTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PercentageCompleted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TodoTasks");

                    b.HasData(
                        new
                        {
                            Id = "orqGEQkjZ4LVcmxxXLvKrXkKNrTNW24rzH",
                            Code = "1RSjwX",
                            CreateAt = new DateTime(2024, 6, 13, 16, 16, 24, 282, DateTimeKind.Utc).AddTicks(2791),
                            Description = "",
                            IsComplete = false,
                            Name = "Task Test",
                            PercentageCompleted = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
