name: Azure Deploy

on:
  push:
   tags:
     - '*'


permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get tag name
      id: get_tag
      run: |
        TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Latest tag: $TAG"
        echo "::set-output name=tag::$TAG"

    - name: Deploy to Azure APP
      run: |
        TAG=${{ steps.get_tag.outputs.TAG }}
        az webapp config container set --name task-manager-app-back --resource-group task-manager --container-image-name ${{ secrets.DOCKER_USERNAME }}/task-manager:$TAG