name: Azure Docker Deploy

on:
  push:
#    tags:
#      - '*'
      branches:
        - main

jobs:
  build-docker-img:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name
        id: get_tag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $TAG"
          echo "::set-output name=tag::$TAG"
      
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          echo "::set-output name=tag::$TAG"
          docker build --file Dockerfile --tag juliofilizzola/task-manager:$TAG .

      - name: Push Docker image
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          docker push -q juliofilizzola/task-manager:$TAG

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Push Docker image to ACR
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          echo ${{ secrets.ACR_PASSWORD }} | docker login filizzola.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin
      
      - name: Build docker ACR
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          docker build -t filizzola.azurecr.io/task-manager:$TAG .

      - name: Push
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          docker push filizzola.azurecr.io/task-manager:$TAG
      
      - name: Deploy to Azure Container Instances
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          az container create --resource-group task-manager --name task-manager --image filizzola.azurecr.io/task-manager:$TAG --ports 80