name: Azure Docker Deploy

on:
  push:
#    tags:
#      - '*'
      branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        id: build-image
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker build -t juliofilizzola/task-manager:$TAG .
          echo "::set-output name=tag::$TAG"

      - name: Push Docker image to ACR
        run: |
          TAG=${{ steps.build-image.outputs.tag }}
          echo ${{ secrets.ACR_PASSWORD }} | docker login filizzola.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push filizzola.azurecr.io/task-manager:$TAG

      - name: Deploy to Azure Container Instances
        run: |
          TAG=${{ steps.build-image.outputs.tag }}
          az container create --resource-group task-manager --name task-manager --image filizzola.azurecr.io/task-manager:$TAG --ports 80