name: Azure Docker Deploy

on:
  push:
#    tags:
#      - '*'
      branches:
        - main

jobs:
  build-docker-img:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get tag name
        id: get_tag
        run: |
          TAG=$(git tag)
          echo "Latest tag: $TAG"
          echo "::set-output name=tag::$TAG"

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          echo "::set-output name=tag::$TAG"
          docker build --file Dockerfile --tag juliofilizzola/task-manager:$TAG .

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-docker-img

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Push Docker image to ACR
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          echo ${{ steps.build-image.outputs.tag }} 
          | docker login filizzola.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push filizzola.azurecr.io/task-manager:$TAG

      - name: Deploy to Azure Container Instances
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          az container create --resource-group task-manager --name task-manager --image filizzola.azurecr.io/task-manager:$TAG --ports 80