name: Azure Docker Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        id: build-image
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker build -t juliofilizzola/task-manager:$TAG .
          echo "::set-output name=tag::$TAG"

      - name: Push Docker image to ACR
        run: |
          TAG=${{ steps.build-image.outputs.tag }}
          echo ${{ secrets.ACR_PASSWORD }} | docker login meuregistro.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push meuregistro.azurecr.io/minha-imagem:$TAG

      - name: Deploy to Azure Container Instances
        run: |
          TAG=${{ steps.build-image.outputs.tag }}
          az group create --name meuGrupoDeRecursos --location eastus
          az container create --resource-group meuGrupoDeRecursos --name meuContainer --image meuregistro.azurecr.io/minha-imagem:$TAG --dns-name-label meuDNS --ports 80