name: Deploy Docker
on:
  push:
   tags:
     - '*'
   branches:
     - main

jobs:
  build-docker-img:
    runs-on:
      - ubuntu-latest

    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name
        id: get_tag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $TAG"
          echo tag=$TAG >> "$GITHUB_OUTPUT"
          echo tag=$TAG >> "GITHUB_STATE"

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          echo "::set-output name=tag::$TAG"
          docker build --file Dockerfile --tag juliofilizzola/task-manager:$TAG .

      - name: Push Docker image
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          docker push -q juliofilizzola/task-manager:$TAG

  build-docker-azure:
    needs:
      - build-docker-img
    runs-on:
      - ubuntu-latest
    steps:
      - env:
          tag: ${{ needs.build-docker-img.outputs.tag }}
        run: echo "$tag"

      - name: Login Docker
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login filizzola.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Pull docker image
        run: |
          TAG=$tag
          docker pull juliofilizzola/task-manager:$TAG

      - name: Tag img docker
        run: |
          TAG=$tag
          docker tag juliofilizzola/task-manager:$TAG filizzola.azurecr.io/task-manager:$TAG

      - name: Push docker img
        run: |
          TAG=$tag
          docker push -q filizzola.azurecr.io/task-manager:$TAG