name: Deploy Docker
on:
  push:
   tags:
     - '*'

jobs:
  build-docker-img:
    runs-on:
      - ubuntu-latest

    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name
        id: get_tag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $TAG"
          echo tag=$TAG >> "$GITHUB_OUTPUT"
          echo tag=$TAG >> "GITHUB_STATE"

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          docker build --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/task-manager:$TAG .

      - name: Push Docker image
        run: |
          TAG=${{ steps.get_tag.outputs.TAG }}
          docker push -q ${{ secrets.DOCKER_USERNAME }}/task-manager:$TAG

  build-docker-azure:
    needs:
      - build-docker-img
    runs-on:
      - ubuntu-latest
    steps:
      - env:
          tag: ${{ needs.build-docker-img.outputs.tag }}
        run: echo "$tag"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Pull Image docker
        run: |
          echo "Pulling image with tag: ${{ needs.build-docker-img.outputs.tag }}"
          
          docker pull ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ needs.build-docker-img.outputs.tag }}

      - name: Login Docker
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_DOCKER_NAME }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      
      - name: Tag img docker
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ needs.build-docker-img.outputs.tag }} ${{ secrets.ACR_DOCKER_NAME }}.azurecr.io/task-manager:${{ needs.build-docker-img.outputs.tag }}

      - name: Push docker img
        run: |
          docker push -q ${{ secrets.ACR_DOCKER_NAME }}.azurecr.io/task-manager:${{ needs.build-docker-img.outputs.tag }}