name: .NET Core

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0' # alterado para a versão 8.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        id: tests
        run: |
          dotnet test --no-build --verbosity normal > test-results.txt
          cat test-results.txt
          echo "$test-results.txt"

      - name: Create test results summary
        id: create-summary
        run: |
          test_count=$(grep -o 'Total tests: [0-9]*' test-results.txt | awk '{sum += $3} END {print sum}')
          passed_count=$(grep -o 'Passed: [0-9]*' test-results.txt |  awk '{sum += $2} END {print sum}')
          failed_count=$(grep -o 'Failed: [0-9]*' test-results.txt | awk '{sum += $2} END {print sum}')
          skipped_count=$(grep -o 'Skipped: [0-9]*' test-results.txt | awk '{sum += $2} END {print sum}')
          echo test_count
          echo passed_count
          echo "::set-output name=test_count::$test_count"
          echo "::set-output name=passed_count::$passed_count"
          echo "::set-output name=failed_count::$failed_count"
          echo "::set-output name=skipped_count::$skipped_count"

      - name: Post test results as a comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const testCount = '${{ steps.create-summary.outputs.test_count || 0 }}';
            const passedCount = '${{ steps.create-summary.outputs.passed_count || 0 }}';
            const failedCount = '${{ steps.create-summary.outputs.failed_count || 0 }}';
            const skippedCount = '${{ steps.create-summary.outputs.skipped_count || 0 }}';
            const commentBody = `
              ## :white_check_mark: Test Results Summary
            
              | Total Tests | Passed Tests | Failed Tests | Skipped Tests |
              |-------------|--------------|--------------|---------------|
              | ${testCount}      | ${passedCount}       | ${failedCount}       | ${skippedCount}        |
            
              ### Details
            
              - **Total tests run:** ${testCount}
              - **Tests passed:** ${passedCount}
              - **Tests failed:** ${failedCount}
              - **Tests skipped:** ${skippedCount}
            
              ### Failed Tests
            
              \`\`\`
              ${'grep -A 1 "Failed" test-results.txt'}
              \`\`\`
            
              _This comment was automatically generated by a GitHub Action._
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });